/*
 * Copyright © 2026 Anti-Matter Studios.
 * This product is released under the MIT licence.
 */


import type { BufferGeometry } from "three";

import type { PlanetGeometryOptions } from "./options";
import { applyPlanetHeightDisplacement } from "./height-displacement";
import { createIcosahedronGeometry } from "./icosahedron";

export type { PlanetGeometryOptions };

/** Type alias for the geometry generated by {@link createPlanetGeometry}. */
export type PlanetGeometry = BufferGeometry;

/**
 * Creates the geometry for a planet.
 *
 * @param options The options for the planet geometry.
 * @returns The planet geometry.
 */
export function createPlanetGeometry(options: PlanetGeometryOptions): PlanetGeometry {
    let geometry = createIcosahedronGeometry(options.radius, options.subdivisions);

    geometry = applyPlanetHeightDisplacement(geometry, options.seed, options.height, options.radius);

    return geometry;
}
